services:
  - type: web
    name: code-editor-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    autoDeploy: true
    healthCheckPath: /docs

