# render.yaml
services:
  - type: web
    name: skoolofcode-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: skoolofcode-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    buildFilter:
      paths:
        - frontend/**
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://skoolofcode-backend.onrender.com

