services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    autoDeploy: true
    healthCheckPath: /docs
    ports:
      - 8000

  - type: static
    name: frontend
    env: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: build
    buildFilter:
      paths:
        - frontend/**
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://code-editor-backend.onrender.com


