services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    rootDir: backend
    autoDeploy: true
    healthCheckPath: /docs

