services:
  - type: web
    name: code-runner-backend
    env: docker
    repo: https://github.com/2001-su/code-editor
    region: oregon
    branch: main
    rootDir: .
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
